name: Astronomer CI - Deploy code

on:
  push:
    branches:
      - main

env:
  ## Set API Token as an environment variable
  ASTRO_API_TOKEN: ${{ eyJhbGciOiJSUzI1NiIsImtpZCI6ImNsb2Q0aGtqejAya3AwMWozdWNqbzJwOHIiLCJ0eXAiOiJKV1QifQ.eyJhcGlUb2tlbklkIjoiY202b3VmamF6MTVxZDAxaXZvZ2dtNXZicSIsImF1ZCI6ImFzdHJvbm9tZXItZWUiLCJpYXQiOjE3Mzg1NzQ2MDUsImlzQXN0cm9ub21lckdlbmVyYXRlZCI6dHJ1ZSwiaXNJbnRlcm5hbCI6ZmFsc2UsImlzcyI6Imh0dHBzOi8vYXBpLmFzdHJvbm9tZXIuaW8iLCJraWQiOiJjbG9kNGhranowMmtwMDFqM3Vjam8ycDhyIiwicGVybWlzc2lvbnMiOlsiYXBpVG9rZW5JZDpjbTZvdWZqYXoxNXFkMDFpdm9nZ201dmJxIiwiZGVwbG95bWVudElkOmNtNm9wdm4zZjE0dTIwMWl2dHJlcXV4Zm0iLCJvcmdhbml6YXRpb25JZDpjbTZkZ2F4YXIxMmplMDFsM3R5dnFlMjFzIiwib3JnU2hvcnROYW1lOmNtNmRnYXhhcjEyamUwMWwzdHl2cWUyMXMiLCJ3b3Jrc3BhY2VJZDpjbTZucnhhYzcxMGljMDFtZGw2N2QzZWRwIl0sInNjb3BlIjoiYXBpVG9rZW5JZDpjbTZvdWZqYXoxNXFkMDFpdm9nZ201dmJxIGRlcGxveW1lbnRJZDpjbTZvcHZuM2YxNHUyMDFpdnRyZXF1eGZtIG9yZ2FuaXphdGlvbklkOmNtNmRnYXhhcjEyamUwMWwzdHl2cWUyMXMgb3JnU2hvcnROYW1lOmNtNmRnYXhhcjEyamUwMWwzdHl2cWUyMXMiLCJzdWIiOiJjbTZkZzhlOXgxMmh6MDFsMzQ2cWZzbTJ5IiwidmVyc2lvbiI6ImNtNm91ZmphejE1cWMwMWl2a211dG54eHEifQ.NnhjUzj6vwnckROX3O-m6F5XnQq7291p7-pBAba6md1QP8FUP8RTxVHWELhftTaFWhyDMTa8UTBDNwoF8uEgu6zVJLjX3onHA6fffKxxIhWvGLy-vK_Np7ObzmvdScvur4yoWIM5EE8ZomI0TQaG2W9MmvAF0_pBWCcVOrSE5HnJMStvRJdAvSl_rSKJvOprqk2a7-1jNC5bGKWbuI8NCF63bk-pfGFMSQV9zDNeoef3h9TROBV0lwIBeLPEgr5yZbkbK7ccOv1Hv5_f2nyQmRVnQ4Dwh-BHUkG6dDsPeoiQfevt_HaOHSInkgDcsVMmDTKpbBph5GwW9b0d1a03mQ }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Astro
      uses: astronomer/deploy-action@v0.9.0
      with:
        deployment-id: <deployment id>
        parse: true
